repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: end-of-file-fixer
      - id: forbid-new-submodules
      - id: trailing-whitespace
        exclude: .*/toml\.ai
        args: [--markdown-linebreak-ext=md]
